### ISSUE TITLE
When using 'chat_campletion_stream_example.dart,' I always receive "null" at the beginning and end.

### ISSUE THREAD

**Issue by ayrshire** [anasfik/openai#11]
When using the code in 'chat_campletion_stream_example.dart,' I always receive "null" at the beginning and end.
The first and the last word are missing.

    final chatStreamTest = OpenAI.instance.chat.createStream(
      model: "gpt-3.5-turbo",
      messages: [
        OpenAIChatCompletionChoiceMessageModel(
          content: "hello",
          role: "user",
        )
      ],
    );

    // Listen to the stream.
    chatStreamTest.listen(
          (streamChatCompletion) {
        final content = streamChatCompletion.choices.first.delta.content;
        print(content);
      },
      onError: (error) {
        print(error);
      },
      cancelOnError: false,
      onDone: () {
        print("Done");
      },
    );

**Comment by anasfik** [comment]
Hello, Thank you for reaching out here, and you're welcome anytime if you have any issues.

The `dart_openai` SDK is made so it reflects the OpenAI APIs, and the `createStream` method reflects the streaming functionality for the response got by OpenAI ends for the chat completions, I did notice the possible `null` value in it (which I don't know why it gets returned, but it is from the OpenAI side, not the SDK's), and this is why the type of `content` property is `String?` not `String`.

So in order to prevent and ignore the `null` responses in the `createStream`, I can guide you through some solutions that you need to do in your code:

### Filtering the `Stream` with `where`:
before listening to the  `chatStreamTest`, you can do:

```dart
final chatStreamTest = OpenAI.instance.chat.createStream(
  model: "gpt-3.5-turbo",
  messages: [
    OpenAIChatCompletionChoiceMessageModel(
      content: "hello",
      role: "user",
    )
  ],
).where((streamChatCompletion) => streamChatCompletion.choices.first.delta.content != null); // add this
```


### Make a condition in the `listen()` method:
```dart
// Listen to the stream.
chatStreamTest.listen(
      (streamChatCompletion) {
final String? content = streamChatCompletion.choices.first.delta.content; // this is a String? type.
if(content != null) {
    print(content); // print only when content is not null.
  }
},
  onError: (error) {
    print(error);
  },
  cancelOnError: false,
  onDone: () {
    print("Done");
  },
);
```

now when you do listen to this stream, It will not include any events where the `streamChatCompletion.choices.first.delta.content`  is `null`, and get you what you expect.

<br>

I don't plan to fix or change this behavior from the SDK internally.

if you have any issues with the SDK please let me know.
have a good day,

**Comment by ayrshire** [comment]
Hello,
Thank you for your response.
I appreciate that both of your solutions can resolve the null string issue.
Yesterday, I noticed that OpenAI's stream consistently omitted the first and last word, but it appears to be functioning correctly now.
Therefore, it appears that this was not a problem with the SDK.
