### ISSUE TITLE
4.1.4 Fails on web, runs fine on iOS

### ISSUE THREAD

**Issue by odedsolutions** [anasfik/openai#124]
I get the following error after updating from 4.0.0 to 4.1.4:

../../.pub-cache/hosted/pub.dev/fetch_api-1.0.2/lib/src/iterator.dart:24:30: Error: `@staticInterop` classes cannot have external extension members with type parameters.
Try using a Dart extension member if you need type parameters instead.
  external IteratorResult<T> next();

It's only when building for web, not iOS.

Any idea? Have tried flutter clean already

Thanks!

**Comment by anasfik** [comment]
Can you show me what is the result of flutter doctor and the version of Flutter and Dart you are using?

**Comment by odedsolutions** [comment]
Of course! using Flutter 3.13.9 and Dart 3.1.5 

`flutter doctor` output:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1 23B74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.84.1)
[✓] VS Code (version 1.82.0-insider)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by anasfik** [comment]
Hi,

I don't see how this issue relates to `dart_openai` since it uses `fetch_client` package and not `fetch_api` which the error refers to, I suspect that there is some incompatibility in your project or from another project that make use of it.

Can you recheck this and provide me with more context if you suspect that this relates to `dart_openai`, otherwise you will need to find the source package (maybe you make use of `fetch_api` in your `pubspec.yaml` file) and fill an issue there.

I will close this for now!

**Comment by odedsolutions** [comment]
It worked. Thanks for the pointers everyone!
