### ISSUE TITLE
Chat completion endpoint does not accept an array of strings in a system message

### ISSUE THREAD

**Issue by misos1** [anasfik/openai#151]
https://platform.openai.com/docs/api-reference/chat/create

``` dart
final systemMessage = OpenAIChatCompletionChoiceMessageModel(
	content: [
		OpenAIChatCompletionChoiceMessageContentItemModel.text(
			"return any message you are given as JSON.",
		),
	],
	role: OpenAIChatMessageRole.assistant,
);
```
```
an error occurred, throwing exception: RequestFailedException(message: '$.messages[1].content' is invalid. Please check the API reference: https://platform.openai.com/docs/api-reference., statusCode: 400)
```

**Comment by anasfik** [comment]
I figured out it was not an issue with the assistant message, rather than an invalid message content type (using `image`  type instead of `image_url`), which is fixed as far as the repo progress.

 an assistant message can have a list `content` normally, I assume you tried the example code at [example/chat_completion_example.dart](https://github.com/anasfik/openai/blob/main/example/lib/chat_completion_example.dart), and so the message at index 1 is actually the [user message](https://github.com/anasfik/openai/blob/7c4712a93a5f236f8c8a6d1879abd2f1f0047862/example/lib/chat_completion_example.dart#L18).

if you are using the image content type there, make sure to set the right model id.
