### ISSUE TITLE
There is no functions for streaming api.

### ISSUE THREAD

**Issue by tolgaerdonmez** [anasfik/openai#75]
The function calling feature is not implemented for streaming api.

**Comment by anasfik** [comment]
Yes, I did removed it for the streaming api currently due to the weird behavior of streaming the function calls letter by letter and not a full `JSON` object that we can parse directly, which breaks the parsing and modelling process. for now, it is availabel for the `Future` method of the chat API and there is a plan to support the `Stream` interface as well.

**Comment by anasfik** [comment]
I'm thinking of having a custom fetching workaround for this behavior, it will be implemented in the future for sure since it is necessary.
