### ISSUE TITLE
No issue - But a question

### ISSUE THREAD

**Issue by jonny7737** [anasfik/openai#92]
Does anyone have an example of how to setup for multiple simultaneous OpenAI API calls?  For example: Updating a user profile (an autonomous background task) while the user is querying for a list of Youtube videos and another autonomous task is processing its own task list to update other data?

This is simple enough in Python but I'd rather use Dart / Flutter.

All responses appreciated.

**Comment by anasfik** [comment]
Hello, sorry for the late reply.

This seems really to be Dart's question rather than this package's. However, you can achieve calling functions in general by using `Future.wait` which accespts a list of `Future`s, put all your call declarations inside it, then resolve it rather than resolving each alone, an example:
```dart
Future future() {
  return Future.delayed(Duration(seconds: 2), () {
    print("resolved");
  });
}

void main() async {
  await Future.wait([
    future(),
    future(),
    future(),
  ]);
}
``` 

this now will resolve all futures at once in 2 seconds rather than resolving one after the other which will take 6 seconds.

Note: with OpenAI, pay attention to its rate limits since it allows 3/min for free accounts.
