### ISSUE TITLE
response total token not found !

### ISSUE THREAD

**Issue by Shawon-mas** [anasfik/openai#98]
When the response comes as a stream, I can not get the total response token. How will get it?
OpenAI Reference :
```
"usage": {
    "prompt_tokens": 9,
    "completion_tokens": 12,
    "total_tokens": 21
  }
```

**Comment by anasfik** [comment]
Thank you for pointing it, it will be resolved..

**Comment by anasfik** [comment]
it appears that the API don't include the usage field when the response is streaming, after researching I found out that you can only do a workaround to calculate it by summing each Stream event/chunk tokens..

- [check this](https://community.openai.com/t/openai-api-get-usage-tokens-in-response-when-set-stream-true/141866/18)

Since this behavior comes from the API itself rather than an issue with the package, it will be closed. I will make sure to point this out in the stream methods code docs.
